# Education Engine — Recommendation Generator
# Produces reasoned recommendations from ranked schools + evidence
# Phase 10.1.7-D: Added locale support for localized output

from .evidence import format_evidence_for_response


def generate_recommendations(
    ranked: list[dict],
    evidence_map: dict[str, list],
    family,
    child,
    top_n: int = 5,
    evidence_chains: list | None = None,
    query_constraints=None,
    locale: str = "en",
    query: str = "",
    school_alias_map: dict | None = None,
    session_id: str = "",  # Phase 10.1.9: trace linkage
) -> str:
    """
    Generate a human-readable recommendation report.
    Includes: top schools, scores, breakdown, evidence links, and reasoning.

    Args:
        ranked: List of ranked school entries with 'school', 'total_score', 'breakdown'
        evidence_map: Map of school_id to evidence items
        family: Family profile
        child: Child profile
        top_n: Number of top schools to include
        evidence_chains: Optional list of evidence chain objects
        query_constraints: Extracted query constraints
        locale: 'zh-TW' or 'en' output language
        query: Original query (for locale auto-detection)
        school_alias_map: Optional {school_id: {locale: name}} mapping

    Returns:
        Localized recommendation string
    """
    # Auto-detect locale from query if not explicitly set
    if not locale and query:
        from ..presentation.locale import detect_locale
        locale = detect_locale(query)

    # Use formatter for localized output (Phase 10.1.7-D/E)
    if locale == "zh-TW":
        from ..presentation.formatter import format_recommendation
        return format_recommendation(ranked, locale=locale, query=query,
                                     school_alias_map=school_alias_map,
                                     query_constraints=query_constraints)

    # English output (default)
    if not ranked:
        return _no_results_message(family, child)

    lines = [
        "=== Hermes Education Recommendation ===",
        "",
        _profile_summary(family, child, query_constraints),
        "",
        f"--- Top {min(top_n, len(ranked))} Schools ---",
    ]

    for i, entry in enumerate(ranked[:top_n], 1):
        school = entry["school"]
        name = school.get("name", "Unknown School")
        score = entry["total_score"]
        breakdown = entry["breakdown"]

        lines.append(f"\n#{i} {name}")
        config_ver = entry.get("config_version", "v1")
        lines.append(f"   Overall Score: {score:.2f} / 1.00  (weights: {config_ver})")
        lines.append(f"   Constraint: {breakdown['constraint']:.2f}  |  "
                      f"Academic: {breakdown.get('academic_signal', 0):.2f}  |  "
                      f"Preference: {breakdown.get('preference_match', 0):.2f}  |  "
                      f"Evidence: {breakdown['evidence']:.2f}")

        # Key attributes (v2 schema)
        attrs = []
        if school.get("district"):
            attrs.append(f"District: {school['district']}")
        if school.get("school_type"):
            attrs.append(f"Type: {school['school_type']}")
        if school.get("student_gender"):
            attrs.append(f"Gender: {school['student_gender']}")
        if school.get("religion"):
            attrs.append(f"Religion: {school['religion']}")
        if attrs:
            lines.append(f"   {'  |  '.join(attrs)}")

        # Reasoning (with constraint match details)
        lines.append(f"   Reasoning: {_build_reasoning(entry, family, child, query_constraints)}")

    # Evidence chains (Phase 8 — source-attributed evidence trace)
    if evidence_chains:
        lines.append(f"\n\n--- Evidence Trace ---")
        for chain in evidence_chains:
            lines.append(chain.format_for_response())
    else:
        lines.append(f"\n\n--- Evidence Summary ---")
        evidence_text = format_evidence_for_response(evidence_map)
        if evidence_text.strip():
            lines.append(evidence_text)
        else:
            lines.append("\n(No detailed evidence available in knowledge base yet.)")

    # Next steps
    lines.append(f"\n\n--- Suggested Next Steps ---")
    lines.append("1. Visit shortlisted schools during open days")
    lines.append("2. Check each school's official website for admission criteria")
    lines.append("3. Prepare application documents (academic records, certificates)")
    lines.append(f"4. Update your family profile with more preferences for better matching")
    lines.append(f"\nGenerated by Hermes Education Engine v1.0")

    # Phase 10.1.9: Trace linkage — Decision Object ↔ Recommendation Trace
    if session_id:
        lines.append(f"Trace ID: {session_id}")

    return "\n".join(lines)


def _profile_summary(family, child, query_constraints=None) -> str:
    """One-line profile summary for the recommendation header."""
    parts = []

    # Show extracted constraints prominently
    if query_constraints:
        if query_constraints.districts:
            parts.append(f"地區：{', '.join(query_constraints.districts)}")
        if query_constraints.gender:
            parts.append(f"性別：{query_constraints.gender}")
        if query_constraints.school_types:
            parts.append(f"類型：{', '.join(query_constraints.school_types)}")
        if query_constraints.interests:
            parts.append(f"興趣：{', '.join(query_constraints.interests)}")

    # Memory-based profile
    if child.grade_level:
        parts.append(f"Level: {child.grade_level}")
    if family.max_annual_fee:
        parts.append(f"Budget: ≤HKD {family.max_annual_fee:,}")

    return f"Profile: {' | '.join(parts)}" if parts else "Profile: (minimal data)"


def _build_reasoning(entry: dict, family, child, query_constraints=None) -> str:
    """Build a reasoning sentence for why this school is recommended.

    Includes: constraint match + academic signal match + evidence source.
    """
    reasons = []
    school = entry["school"]
    breakdown = entry["breakdown"]

    # === CONSTRAINT MATCH REASONS ===
    # District match
    if query_constraints and query_constraints.districts:
        if school.get("district") in query_constraints.districts:
            reasons.append(f"位於{query_constraints.districts[0]}")

    # Gender match
    if query_constraints and query_constraints.gender:
        school_gender = school.get("student_gender", "")
        if school_gender == query_constraints.gender:
            reasons.append("性別符合")
        elif school_gender == "co_ed":
            reasons.append("男女校")

    # School type match
    if query_constraints and query_constraints.school_types:
        school_type = school.get("school_type", "")
        if school_type in query_constraints.school_types:
            reasons.append(f"學校類型：{school_type}")

    # === ACADEMIC SIGNAL MATCH ===
    if query_constraints and query_constraints.interests:
        for interest in query_constraints.interests:
            signal_key = _interest_to_signal_key(interest)
            if signal_key:
                signal_val = school.get(signal_key, "")
                if signal_val == "high":
                    label = signal_key.replace("academic_signal_", "").replace("_", " ")
                    reasons.append(f"{label}能力高")

    # === SCORE-BASED REASONS ===
    if breakdown["constraint"] >= 0.8:
        reasons.append("符合家庭約束條件")
    if breakdown.get("academic_signal", 0) >= 0.5:
        reasons.append("學術特長匹配")
    if breakdown.get("preference_match", 0) >= 0.4:
        reasons.append("學生偏好匹配")

    if not reasons:
        reasons.append("符合基本條件")

    return "；".join(reasons) + "。"


def _interest_to_signal_key(interest: str) -> str | None:
    """Map interest keyword to academic_signal payload field name."""
    mapping = {
        "stem": "academic_signal_science_availability",
        "science": "academic_signal_science_availability",
        "sports": "academic_signal_sports",
        "music": "academic_signal_music",
        "arts": "academic_signal_arts",
        "languages": "academic_signal_language_strength",
    }
    return mapping.get(interest.lower())


def _no_results_message(family, child) -> str:
    """Message when no schools pass the constraints."""
    lines = [
        "=== Hermes Education Recommendation ===",
        "",
        "No schools matched the current constraints.",
        "",
        "Suggestions to broaden your search:",
    ]
    if family.preferred_districts:
        lines.append(f"- Expand preferred districts beyond: {', '.join(family.preferred_districts)}")
    if family.max_annual_fee:
        lines.append(f"- Increase budget above HKD {family.max_annual_fee:,}")
    if family.preferred_language:
        lines.append(f"- Consider schools beyond {family.preferred_language}-medium only")
    lines.append("- Add more preferences to your family profile for better matching")
    return "\n".join(lines)
